name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # للحصول على كامل التاريخ
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Clean node_modules and cache
      run: |
        rm -rf node_modules
        rm -rf .next
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup environment
      run: |
        cp .env.example .env
    
    - name: Generate Prisma Client
      run: npx prisma generate
    
    - name: Build
      run: npm run build
      
    - name: Test directory structure
      run: |
        echo "Checking directory structure..."
        ls -la
        echo "Checking pages directory..."
        ls -la pages || echo "No pages directory found"
        echo "Checking app directory..."
        ls -la app || echo "No app directory found"
        echo "Checking .next directory..."
        ls -la .next || echo "No .next directory found" 